set nocompatible
filetype off

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
set foldmethod=manual
call vundle#begin()

source $HOME/.vim/config/plugins.vimrc
source $HOME/.vim/config/ctrlp.config.vimrc
source $HOME/.vim/config/gui.vimrc
source $HOME/.vim/config/keys.vimrc
source $HOME/.vim/config/rainbow-parentheses.config.vimrc
source $HOME/.vim/config/vim-test.config.vimrc

call vundle#end()
filetype plugin indent on


